/*
 * This file contains many function pointer types and structures for Windows
 * APIs. Many of these structures are not actually needed for this patcher,
 * but were used in the process of developing it. These types make it easy to
 * hook various APIs to manipulate or inspect behavior.
 */

#ifndef COMMON_FNPTR_H
#define COMMON_FNPTR_H

#include <windows.h>

#ifndef DNS_QUERY_REQUEST_VERSION1

typedef struct _DNS_QUERY_REQUEST {
  ULONG   Version;
  PCWSTR  QueryName;
  WORD    QueryType;
  ULONG64 QueryOptions;
  PVOID   pDnsServerList;
  ULONG   InterfaceIndex;
  PVOID   pQueryCompletionCallback;
  PVOID   pQueryContext;
} DNS_QUERY_REQUEST, *PDNS_QUERY_REQUEST;

typedef struct _DNS_QUERY_RESULT {
  ULONG       Version;
  DNS_STATUS  QueryStatus;
  ULONG64     QueryOptions;
  PDNS_RECORD pQueryRecords;
  PVOID       Reserved;
} DNS_QUERY_RESULT, *PDNS_QUERY_RESULT;

typedef struct _DNS_QUERY_CANCEL {
  CHAR Reserved[32];
} DNS_QUERY_CANCEL, *PDNS_QUERY_CANCEL;

#endif

// general
typedef BOOL (WINAPI *PFNDLLMAINPROC)(HANDLE, DWORD, LPVOID);

// ws2_32.dll
typedef int (STDCALL *PFNCONNECTPROC)(SOCKET, const struct sockaddr *, int);
typedef BOOL (STDCALL *PFNCONNECTEXPROC)(SOCKET, const struct sockaddr *, int, PVOID, DWORD, LPDWORD, LPOVERLAPPED);
typedef int (STDCALL *PFNWSACONNECTPROC)(SOCKET, const struct sockaddr *, int, LPWSABUF, LPWSABUF, LPQOS, LPQOS);
typedef WORD (WSAAPI *PFNHTONSPROC)(WORD);
typedef INT (WSAAPI *PFNGETADDRINFO)(PCSTR, PCSTR, const ADDRINFOA *, PADDRINFOA *);
typedef VOID (WSAAPI *PFNFREEADDRINFO)(PADDRINFOA);

// dnsapi.dll
typedef DNS_STATUS (STDCALL *PFNDNSQUERYEXPROC)(PDNS_QUERY_REQUEST pQueryRequest, PDNS_QUERY_RESULT pQueryResults, PDNS_QUERY_CANCEL pCancelHandle);

// advapi32.dll
typedef BOOL (STDCALL *PFNCRYPTDECRYPTPROC)(HCRYPTKEY, HCRYPTHASH, BOOL, DWORD, BYTE *, DWORD *);
typedef BOOL (STDCALL *PFNCRYPTGETHASHPARAMPROC)(HCRYPTHASH, DWORD, BYTE*, DWORD*, DWORD);
typedef BOOL (STDCALL *PFNCRYPTVERIFYSIGNATUREAPROC)(HCRYPTHASH, CONST BYTE *, DWORD, HCRYPTKEY, LPCSTR, DWORD);
typedef BOOL (STDCALL *PFNCRYPTIMPORTKEYPROC)(HCRYPTPROV, CONST BYTE *, DWORD, HCRYPTKEY, DWORD, HCRYPTKEY *);

// user32.dll
typedef int (STDCALL *PFNMESSAGEBOXAPROC)(HWND, LPCSTR, LPCSTR, UINT);
typedef HWND (STDCALL *PFNCREATEWINDOWEXAPROC)(DWORD, LPCSTR, LPCSTR, DWORD, int, int, int, int, HWND, HMENU, HINSTANCE, LPVOID);
typedef LRESULT (STDCALL *PFNSENDMESSAGEPROC)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
typedef BOOL (STDCALL *PFNPEEKMESSAGEAPROC)(LPMSG, HWND, UINT, UINT, UINT);
typedef BOOL (STDCALL *PFNGETMESSAGEAPROC)(LPMSG, HWND, UINT, UINT);
typedef UINT_PTR (STDCALL *PFNSETTIMERPROC)(HWND, UINT_PTR, UINT, TIMERPROC);
typedef int (STDCALL *PFNWVSPRINTFAPROC)(LPSTR, LPCSTR, void *);

// kernel32.dll
typedef HMODULE (STDCALL *PFNLOADLIBRARYAPROC)(LPCSTR);
typedef VOID (STDCALL *PFNFREELIBRARYPROC)(HMODULE);
typedef FARPROC (STDCALL *PFNGETPROCADDRESSPROC)(HMODULE, LPCSTR);
typedef DWORD (STDCALL *PFNGETENVIRONMENTVARIABLEAPROC)(LPCSTR, LPSTR, DWORD);
typedef BOOL (STDCALL *PFNCREATEPROCESSAPROC)(LPCSTR, LPSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES, BOOL, DWORD, LPVOID, LPCSTR, LPSTARTUPINFOA, LPPROCESS_INFORMATION);
typedef BOOL (STDCALL *PFNISWOW64PROCESSPROC)(HANDLE, PBOOL);
typedef HANDLE (STDCALL *PFNCREATEFILEAPROC)(LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
typedef HANDLE (STDCALL *PFNCREATEFILEMAPPINGAPROC)(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCSTR);
typedef HANDLE (STDCALL *PFNOPENMUTEXAPROC)(DWORD, BOOL, LPCSTR);
typedef HANDLE (STDCALL *PFNCREATEMUTEXAPROC)(LPSECURITY_ATTRIBUTES, BOOL, LPCSTR);
typedef DWORD (STDCALL *PFNGETCURRENTTHREADIDPROC)(VOID);
typedef DWORD (STDCALL *PFNGETCURRENTPROCESSIDPROC)(VOID);
typedef VOID (STDCALL *PFNSLEEPPROC)(DWORD);
typedef DWORD (STDCALL *PFNSLEEPEXPROC)(DWORD, BOOL);
typedef DWORD (STDCALL *PFNWAITFORSINGLEOBJECTPROC)(HANDLE, DWORD);
typedef HANDLE (STDCALL *PFNOPENEVENTAPROC)(DWORD, BOOL, LPCSTR);
typedef HANDLE (STDCALL *PFNCREATEEVENTAPROC)(LPSECURITY_ATTRIBUTES lpEventAttributes, BOOL bManualReset, BOOL bInitialState, LPCSTR lpName);
typedef BOOL (STDCALL *PFNGETEXITCODEPROCESSPROC)(HANDLE hProcess, LPDWORD lpExitCode);
typedef HLOCAL (STDCALL *PFNLOCALALLOCPROC)(UINT, UINT);
typedef HLOCAL (STDCALL *PFNLOCALFREEPROC)(HLOCAL);
typedef HMODULE (STDCALL *PFNGETMODULEHANDLEAPROC)(LPCSTR);
typedef DWORD (STDCALL *PFNGETMODULEFILENAMEAPROC)(HMODULE, LPCH, DWORD);
typedef DWORD (STDCALL *PFNGETFILEATTRIBUTESAPROC)(LPCSTR);
typedef VOID (STDCALL *PFNEXITPROCESSPROC)(UINT);
typedef DWORD (STDCALL *PFNGETFILESIZEPROC)(HANDLE, LPDWORD);
typedef BOOL (STDCALL *PFNREADFILEPROC)(HANDLE, LPVOID, DWORD, LPDWORD, LPOVERLAPPED);
typedef BOOL (STDCALL *PFNWRITEFILEPROC)(HANDLE, LPCVOID, DWORD, LPDWORD, LPOVERLAPPED);
typedef BOOL (STDCALL *PFNCLOSEHANDLEPROC)(HANDLE);
typedef LPSTR (STDCALL *PFNLSTRCPYAPROC)(LPSTR, LPCSTR);
typedef DWORD (STDCALL *PFNGETLASTERRORPROC)(VOID);
typedef BOOL (STDCALL *PFNSETENVIRONMENTVARIABLEAPROC)(LPCSTR, LPCSTR);
typedef BOOL (STDCALL *PFNVIRTUALPROTECTEXPROC)(HANDLE, LPVOID, SIZE_T, DWORD, PDWORD);
typedef BOOL (STDCALL *PFNREADPROCESSMEMORYPROC)(HANDLE, LPCVOID, LPVOID, SIZE_T, SIZE_T *);
typedef BOOL (STDCALL *PFNWRITEPROCESSMEMORYPROC)(HANDLE, LPVOID, LPCVOID, SIZE_T, SIZE_T *);
typedef BOOL (STDCALL *PFNFLUSHINSTRUCTIONCACHEPROC)(HANDLE, LPCVOID, SIZE_T);
typedef BOOL (STDCALL *PFNVIRTUALPROTECTPROC)(LPVOID, SIZE_T, DWORD, PDWORD);
typedef HANDLE (STDCALL *PFNGETCURRENTPROCESSPROC)(VOID);
typedef HANDLE (STDCALL *PFNCREATETHREADPROC)(LPSECURITY_ATTRIBUTES, SIZE_T, LPTHREAD_START_ROUTINE, LPVOID, DWORD, LPDWORD);

// wininet.dll
typedef void (STDCALL *PFNINTERNETCONNECTAPROC)(HINTERNET, LPCSTR, INTERNET_PORT, LPCSTR, LPCSTR, DWORD, DWORD, DWORD_PTR);
typedef HINTERNET (STDCALL *PFNINTERNETOPENURLAPROC)(HINTERNET, LPCSTR, LPCSTR, DWORD, DWORD, DWORD_PTR);

// winmm.dll
typedef DWORD (STDCALL *PFNTIMEGETTIMEPROC)();

// ijl15.dll
typedef int(STDCALL *PFNIJLGETLIBVERSIONPROC)();
typedef int(STDCALL *PFNIJLINITPROC)(int);
typedef int(STDCALL *PFNIJLFREEPROC)(int);
typedef int(STDCALL *PFNIJLREADPROC)(int, int);
typedef int(STDCALL *PFNIJLWRITEPROC)(int, int);
typedef int(STDCALL *PFNIJLERRORSTRPROC)(int);

#endif
