name: Format
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: DeterminateSystems/nix-installer-action@v11
    - uses: DeterminateSystems/magic-nix-cache-action@v6
    - name: Check formatting
      run: nix develop --command clang-format --dry-run -Werror src/**/*.c src/**/*.h
