name: MSVC CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: msbuild.exe rugburn.sln "/p:Configuration=Release;Platform=x86"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ijl15.dll
        path: out/Win32/Release/ijl15.dll
