name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v11
    - uses: DeterminateSystems/magic-nix-cache-action@v6
    - name: Compile
      run: nix develop --command make -j8 all
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Automated release.
        draft: true
        prerelease: false
    - name: Upload Build
      id: upload_build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/ijl15.dll
        asset_name: ijl15.dll
        asset_content_type: application/octet-stream
